### ISSUE TITLE
Docker is outdated 

### ISSUE THREAD

**Issue by L4wlz** [OBenned/DiscordSoundbot-Docker#1]
Hi, 
Im very glad to see there was a docker version of this awesome bot :D Thanks to you. 
is it possilbe you can update the docker hub at - https://hub.docker.com/r/obenned/discordsoundbot with an updated version :) the version docker hub is using is a beta 2.2.2 or something like that.. and it will not work any more as darkside mentioned.

**Comment by OBenned** [comment]
Sorry, have been away from this for a long time, but i will look into this asap
